repos:
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.2.0
  #   hooks:
  #     - id: interrogate
  #       exclude: ^(docs|setup.py|tests)
  #       args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: tests/data
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: file-contents-sorter
        files: requirements-dev.txt

  - repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: docs/source/conf.py
        args:
          [
            --max-line-length=105,
            --ignore=E203,
            E501,
            W503,
            --select=select=C,
            E,
            F,
            W,
            B,
            B950,
          ]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        args:
          [
            --project=gcm_filters,
            --multi-line=3,
            --lines-after-imports=2,
            --lines-between-types=1,
            --trailing-comma,
            --force-grid-wrap=0,
            --use-parentheses,
            --line-width=88,
          ]

    # Use black to clean code in python and jupyter notebook cells
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
      - id: black-jupyter
        language_version: python3
        args: [--config=./pyproject.toml]

    # Enforce that notebooks outputs are cleared
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
        args:
          [
            --max-size=1k
          ]

    # Docformatter to format docstrings
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.6.1
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--config=./pyproject.toml]

  # Check on large files as last hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=300']

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.770
  #   hooks:
  #     - id: mypy
  #       exclude: docs/source/conf.py
  #       args: [--ignore-missing-imports]

  # check for code spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
      additional_dependencies: [tomli]
      args: [--toml=./pyproject.toml]
